### ISSUE TITLE
`maplibre_user_icon_shadow has unresolved theme attributes` error

### ISSUE THREAD

**Issue by ssuffian** [maplibre/maplibre-native#1274]
We have a codebase that we use once a year, and now is the time where I am going through and updating all the references and such. I have a snippet of code that seemingly worked last year, but after bumping all of the versions it gives me a runtime error.

```
 val activateOptions = LocationComponentActivationOptions.Builder(requireContext(), it).build()
 map.locationComponent.activateLocationComponent(activateOptions)
```
This code is inside of a map.set_style(...) where `it` is the style.

I'm getting the following traceback:

drawable/maplibre_user_icon_shadow has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
```
 java.lang.RuntimeException
 at android.content.res.Resources.getDrawable(Resources.java:908)
at com.mapbox.mapboxsdk.utils.BitmapUtils.getDrawableFromRes(BitmapUtils.java:183)
at com.mapbox.mapboxsdk.utils.BitmapUtils.getDrawableFromRes(BitmapUtils.java:169)
at com.mapbox.mapboxsdk.location.LayerBitmapProvider.generateShadowBitmap(LayerBitmapProvider.java:30)
at com.mapbox.mapboxsdk.location.LocationLayerController.styleBitmaps(LocationLayerController.java:162)
at com.mapbox.mapboxsdk.location.LocationLayerController.applyStyle(LocationLayerController.java:98)
at com.mapbox.mapboxsdk.location.LocationComponent.applyStyle(LocationComponent.java:496)
at com.mapbox.mapboxsdk.location.LocationComponent.activateLocationComponent(LocationComponent.java:255)
```

I'm using
```
implementation 'org.maplibre.gl:android-sdk:10.2.0'
implementation 'org.maplibre.gl:android-plugin-annotation-v9:1.0.0'
```

Any help would be much appreciated!

**Comment by louwers** [comment]
@ssuffian Thanks for the report. I think I have identified the issue, it should be fixed in the next release.

If you are able to, maybe you can try out building the fix from https://github.com/maplibre/maplibre-native/pull/1275
