### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected

### ISSUE THREAD

**Issue by cameralis** [maplibre/maplibre-native#1287]
**Describe the bug**
Upon running my application, the app crashes with the following error:
```
E/Mbgl-MapChangeReceiver( 7490): Exception in onDidFinishLoadingStyle
E/Mbgl-MapChangeReceiver( 7490): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/com.example-Muj9shysICubnEy4o8YxZw==/base.apk)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxsdk.location.engine.GoogleLocationEngineImpl.requestLocationUpdates(GoogleLocationEngineImpl.java:59)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxsdk.location.engine.GoogleLocationEngineImpl.requestLocationUpdates(GoogleLocationEngineImpl.java:27)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxsdk.location.engine.LocationEngineProxy.requestLocationUpdates(LocationEngineProxy.java:35)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1265)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxsdk.location.LocationComponent.enableLocationComponent(LocationComponent.java:1393)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(LocationComponent.java:517)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxgl.MapboxMapController.enableLocationComponent(MapboxMapController.java:292)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxgl.MapboxMapController.updateMyLocationEnabled(MapboxMapController.java:1775)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxgl.MapboxMapController.access$100(MapboxMapController.java:101)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxgl.MapboxMapController$1.onStyleLoaded(MapboxMapController.java:157)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:962)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:224)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1346)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
E/Mbgl-MapChangeReceiver( 7490):        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1119)
E/Mbgl-MapChangeReceiver( 7490):        at android.os.MessageQueue.nativePollOnce(Native Method)
E/Mbgl-MapChangeReceiver( 7490):        at android.os.MessageQueue.next(MessageQueue.java:386)
E/Mbgl-MapChangeReceiver( 7490):        at android.os.Looper.loop(Looper.java:175)
E/Mbgl-MapChangeReceiver( 7490):        at android.app.ActivityThread.main(ActivityThread.java:7625)
E/Mbgl-MapChangeReceiver( 7490):        at java.lang.reflect.Method.invoke(Native Method)
E/Mbgl-MapChangeReceiver( 7490):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/Mbgl-MapChangeReceiver( 7490):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Platform information:**
- Android 9
- maplibre_gl flutter from git

**Comment by louwers** [comment]
`GoogleLocationEngineImpl` is no longer supported. Please see the release notes.

You can create Flutter issues here: https://github.com/maplibre/flutter-maplibre-gl
