### ISSUE TITLE
[ANDROID] Test Failure "Style isn't initialised"

### ISSUE THREAD

**Issue by abebeos** [maplibre/maplibre-native#1916]
**Describe the bug**

**To Reproduce**

* Do initial build as described here #1913

Run "All Tests" using an Emulated Device (tried with `Pixel 7 API 33`, `Pixel 3a API 31`)

```
12-05 15:51:30.398  1257  4414 I Icing   : Indexing com.google.android.gms-apps from com.google.android.gms
12-05 15:51:30.404  2564  2564 I Finsky  : [2] DownloadServiceReceiver.c(4): DSR: Download completion broadcast received by main process
12-05 15:51:30.404  2564  2564 I Finsky  : [2] rkb.f(6): RM: receive resource status onSuccess com.google.android.apps.restore:com.google.android.apps.restore reason: early_update isis: RQuAKNz2RKSZjvarG1Cxjw, 3, 200
12-05 15:51:30.420  3125  3588 D EGL_emulation: app_time_stats: avg=3487.21ms min=2.41ms max=30712.96ms count=9
12-05 15:51:30.447  2564  2564 I Finsky  : [2] kxk.u(6): Installer::IT: com.google.android.apps.restore to state 50 (isid: RQuAKNz2RKSZjvarG1Cxjw)
12-05 15:51:30.466  3125  3434 E TestRunner: failed: testLatLngBoundsTiltedRotated(org.maplibre.android.camera.CameraUpdateFactoryTest)
12-05 15:51:30.466  3125  3434 E TestRunner: ----- begin exception -----
12-05 15:51:30.467  3125  3434 E TestRunner: junit.framework.AssertionFailedError: Style isn't initialised
12-05 15:51:30.467  3125  3434 E TestRunner: 	at junit.framework.Assert.fail(Assert.java:50)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at junit.framework.Assert.assertTrue(Assert.java:20)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at junit.framework.Assert.assertNotNull(Assert.java:218)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.maplibre.android.testapp.activity.BaseTest.validateTestSetup(BaseTest.java:76)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.maplibre.android.testapp.activity.BaseTest.holdTestRunnerForStyleLoad(BaseTest.java:108)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.maplibre.android.testapp.activity.BaseTest.beforeTest(BaseTest.java:54)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:76)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:136)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:543)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
12-05 15:51:30.467  3125  3434 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2361)
12-05 15:51:30.468  3125  3434 E TestRunner: ----- end exception -----
12-05 15:51:30.469  2564  2564 I Finsky  : [2] kxk.u(92): Installer::IT: Start postprocessing download for com.google.android.apps.restore (isid: RQuAKNz2RKSZjvarG1Cxjw)
12-05 15:51:30.479  3125  3434 I TestRunner: finished: testLatLngBoundsTiltedRotated(org.maplibre.android.camera.CameraUpdateFactoryTest)

junit.framework.AssertionFailedError: Style isn't initialised
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertNotNull(Assert.java:218)
at org.maplibre.android.testapp.activity.BaseTest.validateTestSetup(BaseTest.java:76)
at org.maplibre.android.testapp.activity.BaseTest.holdTestRunnerForStyleLoad(BaseTest.java:108)
at org.maplibre.android.testapp.activity.BaseTest.beforeTest(BaseTest.java:54)
```

**Comment by louwers** [comment]
Did you set a MapTiler API key?

**Comment by abebeos** [comment]
> Did you set a MapTiler API key?

Where is this documented?
