### ISSUE TITLE
Flaky Instrumentation Tests

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#2488]
- [x] Crashes in `DefaultRefDeleter`, #2487 but may show up in other places.
- [x] MapTiler style not available, switching to other style in #2438, but ideally we run the instrumentation tests completely offline
- [ ] `org.maplibre.android.testapp.style.CustomGeometrySourceTest.threadsRestartedWhenSourceReAddedTest`

<details>
<summary>CustomGeometrySourceTest.kt:60</summary>

androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: Threads should be restarted when the source is re-added to the map.
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1724)
at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:3)
at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:1)
at androidx.test.espresso.base.DefaultFailureHandler$TypedFailureHandler.handle(DefaultFailureHandler.java:4)
at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:5)
at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:8)
at org.maplibre.android.testapp.action.MapLibreMapAction.invoke(MapLibreMapAction.java:43)
at org.maplibre.android.testapp.style.CustomGeometrySourceTest.threadsRestartedWhenSourceReAddedTest(CustomGeometrySourceTest.kt:60)
... 37 trimmed
Caused by: java.lang.AssertionError: Threads should be restarted when the source is re-added to the map.
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.maplibre.android.testapp.style.CustomGeometrySourceTest.threadsRestartedWhenSourceReAddedTest$lambda$4(CustomGeometrySourceTest.kt:68)
at org.maplibre.android.testapp.style.CustomGeometrySourceTest.$r8$lambda$zaNEdhDckVle0avVMGM_0r-niNg(Unknown Source:0)
at org.maplibre.android.testapp.style.CustomGeometrySourceTest$$ExternalSyntheticLambda0.onInvokeAction(D8$$SyntheticClass:0)
at org.maplibre.android.testapp.action.MapLibreMapAction.perform(MapLibreMapAction.java:39)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:25)
at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:7)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7870)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
</details>

- [ ] androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: Camera position should match expected:<Target: LatLng [latitude=12.00000000000003, longitude=12.0, altitude=0.0], Zoom:12.0, Bearing:-0.0, Tilt:0.0, Padding:[0.0, 0.0, 0.0, 0.0]> but was:<Target: LatLng [latitude=12.000000000000018, longitude=12.0, altitude=0.0], Zoom:12.0, Bearing:-0.0, Tilt:0.0, Padding:[0.0, 0.0, 0.0, 0.0]>

- [ ] org.maplibre.android.location.LocationComponentTest$cameraPositionAdjustedToTrackingModeWhenComponentEnabled

expected:<15.0> but was:<0.0> 

- [ ] scrollRecyclerView(org.maplibre.android.integration.GLSurfaceViewReuseTest)

<details>
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[SCROLLABLE=true]
	at androidx.test.uiautomator.UiScrollable.scrollBackward(UiScrollable.java:427)
	at androidx.test.uiautomator.UiScrollable.scrollToBeginning(UiScrollable.java:472)
	at androidx.test.uiautomator.UiScrollable.scrollToBeginning(UiScrollable.java:489)
	at androidx.test.uiautomator.UiScrollable.scrollIntoView(UiScrollable.java:255)
	at org.maplibre.android.integration.BaseIntegrationTestKt.scrollRecyclerViewTo(BaseIntegrationTest.kt:39)
	at org.maplibre.android.integration.GLSurfaceViewReuseTest.scrollRecyclerView(GLSurfaceViewReuseTest.kt:24)
</details>

- [ ] scrollRecyclerView(org.maplibre.android.integration.TextureViewReuseTest)

<details>
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[SCROLLABLE=true]
	at androidx.test.uiautomator.UiScrollable.scrollBackward(UiScrollable.java:427)
	at androidx.test.uiautomator.UiScrollable.scrollToBeginning(UiScrollable.java:472)
	at androidx.test.uiautomator.UiScrollable.scrollToBeginning(UiScrollable.java:489)
	at androidx.test.uiautomator.UiScrollable.scrollIntoView(UiScrollable.java:255)
	at org.maplibre.android.integration.BaseIntegrationTestKt.scrollRecyclerViewTo(BaseIntegrationTest.kt:39)
	at org.maplibre.android.integration.TextureViewReuseTest.scrollRecyclerView(TextureViewReuseTest.kt:25)
</details>

- [ ] animators_cameraLatLngBearingCorrect

passes, or fails with (depending on device)
expected:<15.0> but was:<0.0>
expected:<30.0> but was:<25.958044673317847>

<details>
androidx.test.espresso.base.AssertionErrorHandler$AssertionFailedWithCauseError: expected:<15.0> but was:<0.0>
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1720)
	at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:3)
	at androidx.test.espresso.base.AssertionErrorHandler.handleSafely(AssertionErrorHandler.java:1)
	at androidx.test.espresso.base.DefaultFailureHandler$TypedFailureHandler.handle(DefaultFailureHandler.java:4)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:5)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:11)
	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:8)
	at org.maplibre.android.location.LocationComponentTest.executeComponentTest(LocationComponentTest.kt:1873)
	at org.maplibre.android.location.LocationComponentTest.animators_cameraLatLngBearingCorrect(LocationComponentTest.kt:1114)
	... 38 trimmed
Caused by: java.lang.AssertionError: expected:<15.0> but was:<0.0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:685)
	at org.maplibre.android.location.LocationComponentTest$animators_cameraLatLngBearingCorrect$componentAction$1.onLocationComponentAction(LocationComponentTest.kt:1098)
	at org.maplibre.android.location.utils.LocationComponentAction.perform(LocationComponentAction.kt:27)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:25)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:7)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
</details>

- [ ] org.maplibre.android.integration.GLSurfaceViewReopenTest

 Permission Denial: package=org.maplibre.android.testapp.test does not belong to uid=10241

- [ ] org.maplibre.android.integration.QueryRenderedFeaturesBoxCountTest

Permission Denial: package=org.maplibre.android.testapp.test does not belong to uid=10241

- [ ] org.maplibre.android.integration.TextureViewReopenTest

package=org.maplibre.android.testapp.test does not belong to uid=10300

**Comment by louwers** [comment]
07-29 16:14:10.134 22867 22867 E Mbgl-NativeMapView: You're calling `addAnnotationIcon` after the `MapView` was destroyed, were you invoking it after `onDestroy()`?
07-29 16:14:10.134 22867 22867 D AndroidRuntime: Shutting down VM
--------- beginning of crash

07-29 16:14:10.136 22867 22867 D MonitoringInstr: org.maplibre.android.MapStrictModeException: Map detected an error that would fail silently otherwise: You're calling `addAnnotationIcon` after the `MapView` was destroyed, were you invoking it after `onDestroy()`?
