### ISSUE TITLE
Crash on MapLibre-Native android-v11.1.0

### ISSUE THREAD

**Issue by alasram** [maplibre/maplibre-native#2800]
Run into a crash while using `android-v11.1.0` (not reproducible):
```
E  FATAL EXCEPTION: main
Process: PID: 3199
java.lang.NullPointerException: Attempt to invoke virtual method 'double org.maplibre.android.geometry.LatLng.getLatitude()' on a null object reference
at org.maplibre.android.location.Utils.immediateAnimation(Utils.java:107)
at org.maplibre.android.location.LocationCameraController.transitionToCurrentLocation(LocationCameraController.java:177)
at org.maplibre.android.location.LocationCameraController.setCameraMode(LocationCameraController.java:126)
at org.maplibre.android.location.LocationComponent.setCameraMode(LocationComponent.java:387)
```

**Comment by louwers** [comment]
Related? https://github.com/maplibre/maplibre-native/issues/2951

**Comment by litrik** [comment]
We've also just seen this appear in our Crashlytics.
We are using MapLibre 13.3.0.
Unfortunately we can't reproduce this either ☹️ 

```kotlin
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'double org.maplibre.android.geometry.LatLng.getLatitude()' on a null object reference
at org.maplibre.android.location.Utils.immediateAnimation(Utils.java)
at org.maplibre.android.location.LocationCameraController.transitionToCurrentLocation(LocationCameraController.java:177)
at org.maplibre.android.location.LocationCameraController.setCameraMode(LocationCameraController.java:126)
at org.maplibre.android.location.LocationComponent.setCameraMode(LocationComponent.java:387)
at org.maplibre.android.location.LocationComponent.setCameraMode(LocationComponent.java:351)
at org.maplibre.android.location.LocationComponent.setCameraMode(LocationComponent.java:326)
```
