### ISSUE TITLE
NullPointerException in MapSnapshotter - Maplibre Native 11.0.1 or later

### ISSUE THREAD

**Issue by geolives-contact** [maplibre/maplibre-native#2869]
**Describe the bug**

When requesting a map snapshot via the MapSnapshotter, a NullPointerException is always triggered : 

`java.lang.NullPointerException
    at org.maplibre.android.snapshotter.MapSnapshotter.createScaledLogo(MapSnapshotter.kt:572)
    at org.maplibre.android.snapshotter.MapSnapshotter.getAttributionMeasure(MapSnapshotter.kt:490)
    at org.maplibre.android.snapshotter.MapSnapshotter.drawOverlay(MapSnapshotter.kt:483)
    at org.maplibre.android.snapshotter.MapSnapshotter.addOverlay(MapSnapshotter.kt:479)
    at org.maplibre.android.snapshotter.MapSnapshotter.onSnapshotReady$lambda$1(MapSnapshotter.kt:615)
    at org.maplibre.android.snapshotter.MapSnapshotter.$r8$lambda$PXYXPNpROqI-KORQGVOb-8MagSo(Unknown Source:0)
    at org.maplibre.android.snapshotter.MapSnapshotter$$ExternalSyntheticLambda0.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:222)
    at android.os.Looper.loop(Looper.java:314)
    at android.app.ActivityThread.main(ActivityThread.java:8602)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)`

**To Reproduce**

Request a map snapshot via the MapSnapshotter with Maplibre Native 11.0.1 or later.

**Expected behavior**

The snapshot of the map should be returned.

**Platform information**

- OS: Android 14 (not tested on other Android version)
- Android Platform SDK 34

**Additional context**

The problem always occurs with MapLibre Native 11.0.1 and 11.1.0
The problem doesn't occur with previous Maplibre Native versions (for example 11.0.0)

**Comment by louwers** [comment]
Does your style have any attribution information?
