### ISSUE TITLE
MabLibre android-v11.1.0 error `Calling getSourceAs when a newer style is loading/has loaded`

### ISSUE THREAD

**Issue by alasram** [maplibre/maplibre-native#2876]
On switching away from and back a MapLibre app using MabLibre `android-v11.1.0` we're getting the exception `Calling getSourceAs when a newer style is loading/has loaded.`

Callstack:

```
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: FATAL EXCEPTION: main
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: Process: com.oem.application, PID: 19038
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: java.lang.IllegalStateException: Calling getSourceAs when a newer style is loading/has loaded.
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.maps.Style.validateState(Style.java:776)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.maps.Style.getSourceAs(Style.java:147)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.SymbolLocationLayerRenderer.refreshSource(SymbolLocationLayerRenderer.java:322)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.SymbolLocationLayerRenderer.setLocationPoint(SymbolLocationLayerRenderer.java:332)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.SymbolLocationLayerRenderer.setLatLng(SymbolLocationLayerRenderer.java:163)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.LocationLayerController$1.onNewAnimationValue(LocationLayerController.java:265)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.LocationLayerController$1.onNewAnimationValue(LocationLayerController.java:262)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.MapLibreAnimator.postUpdates(MapLibreAnimator.java:106)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.MapLibreAnimator.onAnimationUpdate(MapLibreAnimator.java:93)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1566)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:692)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:655)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at android.animation.ValueAnimator.start(ValueAnimator.java:1087)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at android.animation.ValueAnimator.startWithoutPulsing(ValueAnimator.java:1099)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1149)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1234)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at android.animation.AnimatorSet.start(AnimatorSet.java:729)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at android.animation.AnimatorSet.start(AnimatorSet.java:684)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.MapLibreAnimatorSetProvider.startAnimation(MapLibreAnimatorSetProvider.java:31)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.LocationAnimatorCoordinator.playAnimators(LocationAnimatorCoordinator.java:396)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.LocationAnimatorCoordinator.resetAllLayerAnimations(LocationAnimatorCoordinator.java:483)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.LocationComponent.updateAnimatorListenerHolders(LocationComponent.java:1387)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.LocationComponent.access$1200(LocationComponent.java:101)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.LocationComponent$8.onCameraTrackingChanged(LocationComponent.java:1525)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.LocationCameraController.notifyCameraTrackingChangeListener(LocationCameraController.java:354)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.LocationCameraController.setCameraMode(LocationCameraController.java:125)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.LocationComponent.setCameraMode(LocationComponent.java:387)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.LocationComponent.setCameraMode(LocationComponent.java:351)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.LocationComponent.setCameraMode(LocationComponent.java:326)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.location.LocationComponent$10.onDeveloperAnimationStarted(LocationComponent.java:1550)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.maps.MapLibreMap.notifyDeveloperAnimationListeners(MapLibreMap.java:2504)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.maps.MapLibreMap.moveCamera(MapLibreMap.java:531)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at org.maplibre.android.maps.MapLibreMap.setCameraPosition(MapLibreMap.java:507)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at com.oem.application.maplibre.renderer.camera.SdkCameraPropertiesApplier.applyWithNoAnimation(SdkCameraPropertiesApplier.kt:126)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at com.oem.application.camera.MapCameraImpl.setCameraWithNoAnimation(MapCameraImpl.kt:810)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at com.oem.application.Fragment.moveCameraToCurLocation(MapFragment.kt:250)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at com.oem.application.MapFragment.onStart(MapFragment.kt:190)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performStart(Fragment.java:3162)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:588)
2024-09-22 13:22:41.416898 -0700 19038 19038 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1424)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2968)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:2893)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:274)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:359)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at com.oem.application.Activity.onStart(Activity.kt:66)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8018)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2024-09-22 13:22:41.418551 -0700 19038 19038 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:949)
```

**Comment by pstanoev** [comment]
This is usually client side error. Location updates (blue dot) need to be disabled if you are hiding the map.

**Comment by alasram** [comment]
Thanks @pstanoev for looking into this. 
Can you elaborate on `Location updates (blue dot) need to be disabled if you are hiding the map.`?
Do we need to call a specific [LocationComponent function](https://maplibre.org/maplibre-native/android/api/-map-libre%20-native%20-android/org.maplibre.android.location/-location-component/index.html) in response to a `onPause` and `onResume` events?

**Comment by Sideness** [comment]
We have the same problem here. We had the same exception on some actions that we launched and we were able to fix them. But we also have this exact same exception on an animation that doesn't point to any of our code.
Did you manage to fix it?

**Comment by alasram** [comment]
@Sideness on what what version have you seen this crash?
Issue is only seen on MabLibre android-v11.1.0. We never had such a crash on newer version. We've been using 11.6 for more than a month without any MapLibre crash

**Comment by tvaknin** [comment]
@alasram I'm using 11.7.1 and got this as well. 

`          Fatal Exception: java.lang.IllegalStateException: Calling getSourceAs when a newer style is loading/has loaded.
       at org.maplibre.android.maps.Style.validateState(Style.java:776)
       at org.maplibre.android.maps.Style.getSourceAs(Style.java:147)
       at org.maplibre.android.location.SymbolLocationLayerRenderer.refreshSource(SymbolLocationLayerRenderer.java:322)
       at org.maplibre.android.location.SymbolLocationLayerRenderer.setBearingProperty(SymbolLocationLayerRenderer.java:338)
       at org.maplibre.android.location.SymbolLocationLayerRenderer.setCompassBearing(SymbolLocationLayerRenderer.java:173)
       at org.maplibre.android.location.LocationLayerController$3.onNewAnimationValue(LocationLayerController.java:281)
       at org.maplibre.android.location.LocationLayerController$3.onNewAnimationValue(LocationLayerController.java:278)
       at org.maplibre.android.location.MapLibreAnimator.postUpdates(MapLibreAnimator.java:106)
       at org.maplibre.android.location.MapLibreAnimator.onAnimationUpdate(MapLibreAnimator.java:93)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1558)
       at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1349)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1481)
       at android.animation.ValueAnimator.pulseAnimationFrame(ValueAnimator.java:1500)
       at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1170)
       at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1061)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
       at android.view.Choreographer.doCallbacks(Choreographer.java:854)
       at android.view.Choreographer.doFrame(Choreographer.java:785)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7562)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
        `

**Comment by alasram** [comment]
Our crash reports all point to android-v11.1.0. The issue is still there if you are seeing on 11.7.1 @tvaknin. We have probably made code changes that are hiding the issue on newer versions

**Comment by ravenfeld** [comment]
I have the same problem with 11.8.0

**Comment by michalgwo** [comment]
Checking if [isFullyLoaded](https://maplibre.org/maplibre-native/android/api/-map-libre%20-native%20-android/org.maplibre.android.maps/-style/is-fully-loaded.html?query=open%20fun%20isFullyLoaded():%20Boolean) is `true` before every interaction with a style (i.e. before `getSourceAs`) usually solves this error for me.

**Comment by ravenfeld** [comment]
It's in the `LocationComponent`, so we don't do the `getSourceAs` ourselves.
