### ISSUE TITLE
`MapLibreMap.getVisibleRegion(true).latLngBounds` returns invalid coordinates

### ISSUE THREAD

**Issue by westnordost** [maplibre/maplibre-native#2951]
**Describe the bug**
`MapLibreMap.visibleRegion.latLngBounds` in certain circumstances returns a `LatLngBounds` with an invalid longitude (e.g. `longitude=422.6005507684057`).

Related crash report:
```
java.lang.IllegalArgumentException: Latitude 89.99986064045117, longitude 422.6005507684057 is not a valid position
	at de.westnordost.streetcomplete.data.osm.mapdata.LatLon$Companion.checkValidity(Unknown Source:73)
	at de.westnordost.streetcomplete.data.osm.mapdata.LatLon.<init>(SourceFile:0)
	at de.westnordost.streetcomplete.data.osm.mapdata.BoundingBox.<init>(SourceFile:0)
	at de.westnordost.streetcomplete.screens.main.map.maplibre.PositionKt.toBoundingBox(Unknown Source:16)
	at de.westnordost.streetcomplete.screens.main.map.maplibre.PositionKt.screenAreaToBoundingBox(Unknown Source:16)
	at de.westnordost.streetcomplete.screens.main.map.MapFragment.getDisplayedArea(Unknown Source:4)
```

(`MapFragment.getDisplayedArea()` calls `mapLibreMap.projection.getVisibleRegion(true).latLngBounds`)

**To Reproduce**
Move the screen to overlap with the 180th meridian. Observe the result of `VisibleRegion.latLngBounds`.
Maybe there are other ways to reproduce this, too.

**Expected behavior**
`LatLngBounds` should always contain valid latitude and longitude coordinates.

**Platform information:**
 - Android
 - Maplibre v11.5.1

**Additional context**
Every `VisibleRegion` (= trapezoid of four LatLng coordinates at screen borders) has a `LatLngBounds` (= aligned rectangle of LatLng coordinates). A documentation comment states 

> since 7.0.0 LatLngBounds cannot be wrapped any more, i.e longitudeWest has to be less or equal to longitudeEast.

Fair enough, but then, what is the `latLngBounds` of a `VisibleRegion` at the 180th meridian? Looks to me that it should be two `LatLngBounds` in that case - one on the left and one on the right side of the 180th meridian.
In any case, currently, that documentation comment seems to be wrong anyway.

**Comment by johan12345** [comment]
As far as I understand it, the current behavior is consistent with the comment as long as the longitude range covered by the map is less than 360°: To represent `LatLngBounds` crossing the antimeridian with `longitudeWest <= longitudeEast`, `longitudeEast` is set to a value larger than 180.

However, I see very strange behavior in the case that the map is so far zoomed out (and wide enough in aspect ratio) that it covers more than 360° in longitude - so that at least some meridians are visible more than once. In this case, the coordinates given by `getVisibleRegion().latLngBounds` really seem to be incorrect.

For example, with the southwest corner at `(-70, 0)` and northeast at `(81, 117)` (crossing the antimeridian once, i.e. covering 477° of longitude), the `latLngBounds` I get are swapped, with the western longitude at `117` and eastern longitude at `360` (appearing to cover only 243°). Similar errors happen when the antimeridian is crossed twice.
