### ISSUE TITLE
Android test app: WithinExpressionActivity crashes "null cannot be cast to non-null type"

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre-native#649]
**To Reproduce**
1. Run app, launch WithinExpressionActivity
2. Move around a bit
3. App crashes

**Describe the bug**

```
2023-01-04 14:02:57.913 5131-5131/com.mapbox.mapboxsdk.testapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.mapboxsdk.testapp, PID: 5131
    java.lang.NullPointerException: null cannot be cast to non-null type com.mapbox.mapboxsdk.style.layers.SymbolLayer
        at com.mapbox.mapboxsdk.testapp.activity.turf.WithinExpressionActivity.optimizeStyle(WithinExpressionActivity.kt:161)
        at com.mapbox.mapboxsdk.testapp.activity.turf.WithinExpressionActivity.runnable$lambda$0(WithinExpressionActivity.kt:35)
        at com.mapbox.mapboxsdk.testapp.activity.turf.WithinExpressionActivity.$r8$lambda$MxZivj_AvMdsXazQ_pM5SkO-J_E(Unknown Source:0)
        at com.mapbox.mapboxsdk.testapp.activity.turf.WithinExpressionActivity$$ExternalSyntheticLambda1.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Expected behavior**
App does not crash

**Platform information (please complete the following information):**
 - OS: Android
 - Version `main`

**Comment by louwers** [comment]
DistanceExpressionActivity has the same problem.

I am fixing the cast which solves the crash but I don't think the examples are working as intended.

**Comment by louwers** [comment]
I am not seeing this anymore.
